version: '3.8'
services:
  mysqldb:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: PassW0rd
      MYSQL_PASSWORD: PassW0rd
    volumes:
      - /app:/var/lib/mysql
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080